CREATE TABLE Sales
(company CHAR(1) NOT NULL,
 year	 INTEGER NOT NULL,
 sale	 INTEGER NOT NULL,
  CONSTRAINT pk_sales PRIMARY KEY (company, year));

INSERT INTO Sales VALUES('A', 2002, 50);

CREATE TABLE Sales2
(company CHAR(1) NOT NULL,
 year	 INTEGER NOT NULL,
 sale	 INTEGER NOT NULL,
 var     CHAR(1),
  CONSTRAINT pk_sales2 PRIMARY KEY (company, year));

CREATE TABLE Foo
( p_key INTEGER PRIMARY KEY,
  col_a INTEGER
);

INSERT INTO Foo VALUES( 1, 100 );
INSERT INTO Foo VALUES( 2, 200 );
INSERT INTO Foo VALUES( 3, 300 );
INSERT INTO Foo VALUES( 4, 400 );

SELECT col_a FROM Foo WHERE p_key = 1
