CREATE TABLE Sales
(company CHAR(1) NOT NULL,
 year	 INTEGER NOT NULL,
 sale	 INTEGER NOT NULL,
  CONSTRAINT pk_sales PRIMARY KEY (company, year));

INSERT INTO Sales VALUES('A', 2002, 50);

CREATE TABLE Sales2
(company CHAR(1) NOT NULL,
 year	 INTEGER NOT NULL,
 sale	 INTEGER NOT NULL,
 var     CHAR(1),
  CONSTRAINT pk_sales2 PRIMARY KEY (company, year));

CREATE TABLE Foo
( p_key INTEGER PRIMARY KEY,
  col_a INTEGER
);

INSERT INTO Foo VALUES( 1, 100 );
INSERT INTO Foo VALUES( 2, 200 );
INSERT INTO Foo VALUES( 3, 300 );
INSERT INTO Foo VALUES( 4, 400 );

SELECT col_a FROM Foo WHERE p_key = 1

INSERT INTO Sales2
SELECT company, year, sale,
	CASE SIGN(sale - MAX(sale) 
			OVER( PARTITION BY company ORDER BY year
				ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) )
	WHEN 0 THEN '='
	WHEN 1 THEN '+'
	WHEN -1 THEN '-'
	ELSE NULL END AS var
  FROM Sales;
